name: firstly
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  animated_bottom_navigation_bar: ^1.4.0
  page_transition: ^2.2.1
  url_launcher: ^6.1.14
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.0.0
  just_audio: ^0.9.46
  dash_chat_2: ^0.0.21
  chat_gpt_sdk: ^2.2.8
  http: ^1.3.0

  carousel_slider: ^4.2.1
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  cloud_firestore: ^5.6.4
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

